# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32953d5f3fa27dce99603e8fe0800483bc3423b89d88899b47a839874768b460af3b570cf9195591e40818af1fe32d5e39b4db85fc3e6d26ede2e62e9fb1761c

test:
  secret_key_base: b21aa0fe71e0ecdc85846ec6bcaf5757b09fffcf2b65ce24ebb38b7e6bddcb141d62d43ab967b649a2dd1793f7811889306c1a6c52bcb69f9c22c240014a230d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
